Import('env', 'object_files')

libs = [ "pthread", "protobuf", "rt", "cryptopp" ]

src = [
    "Backoff.cc",
    "Client.cc",
    "ClientImpl.cc",
    "LeaderRPC.cc",
    "MockClientImpl.cc",
    "SessionManager.cc",
    "Util.cc",
    "../Server/Globals.cc",
    "../Server/ClientService.cc",
    "../Server/ControlService.cc",
    "../Server/Globals.cc",
    "../Server/RaftConsensus.cc",
    "../Server/RaftConsensusInvariants.cc",
    "../Server/RaftService.cc",
    "../Server/ServerStats.cc",
    "../Server/StateMachine.cc",
]
object_files['Client'] = env.StaticObject(src)

env.Default([
    env.Program("ServerControl",
                (["ServerControl.cc", "#build/liblogcabin.a"]),
                LIBS = libs),
])
